version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /home/steve/Documents/FormationIA/Certif/ProjetBloc1/volumes/postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    user: "${UID}:${GID}"
    volumes:
      - /home/steve/Documents/FormationIA/Certif/ProjetBloc1/volumes/mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"