
services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../volumes/postgres_data:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: elasticsearch-single
    environment:
      - node.name=elasticsearch-single
      - cluster.name=single-node-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../volumes/elk_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"